#!/bin/bash
set -e

# Dynamically inject GITHUB_PATH into current PATH so node and npm can be found
if [ -f "$GITHUB_PATH" ]; then
    while IFS= read -r line; do
        export PATH="$line:$PATH"
    done < "$GITHUB_PATH"
fi

echo "[CI] Node version: $(node -v)"
echo "[CI] NPM version: $(npm -v)"

# Install APK if provided
if [ -n "$APK_PATH" ] && [ -f "$APK_PATH" ]; then
    echo "[CI] Installing APK: $APK_PATH"
    adb install -r "$APK_PATH"
else
    echo "[CI] APK_PATH not provided or file not found. Assuming app is pre-installed or mocked."
fi

# Change directory to where WDIO and package.json are located
cd AIBloodLossEstimatorFluidMonitorAppium || exit 1

# Start Appium Server in background
echo "[CI] Starting Appium server..."
npx appium --log-level warn > /tmp/appium.log 2>&1 &
APPIUM_PID=$!

# Wait for Appium to respond on port 4723
echo "[CI] Waiting for Appium to boot on port 4723..."
TIMEOUT=30
while ! curl -s http://127.0.0.1:4723/status > /dev/null; do
    sleep 1
    TIMEOUT=$((TIMEOUT - 1))
    if [ $TIMEOUT -eq 0 ]; then
        echo "[CI] FATAL: Appium failed to start within 30 seconds."
        cat /tmp/appium.log
        node utils/generateFallbackReport.js
        exit 1
    fi
done
echo "[CI] Appium server is up and running."

# Run WebDriverIO
echo "[CI] Executing WDIO Tests..."
if ! node node_modules/@wdio/cli/bin/wdio.js run wdio.conf.js $WDIO_CLI_ARGS; then
    echo "[CI] WDIO process exited with an error code."
    # If HTML report wasn't generated by onComplete (fatal crash), run fallback
    if [ ! -f "execution-report.html" ]; then
        node utils/generateFallbackReport.js
    fi
    exit 1
fi

echo "[CI] WDIO Run Completed Successfully."
kill $APPIUM_PID || true
